# Generated by Django 6.0.1 on 2026-03-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto_binaria',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
